apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-rest-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      role: api-rest
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: api-rest
    spec:
      containers:
        - name: competent-austin
          image: marce224/api-node:latest
          ports:
            - containerPort: 3000
